# Make sure to check the documentation at https://goreleaser.com

version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
    - goos: windows
      formats: [zip]

nfpms:
  - package_name: go-release-blueprint
    homepage: https://github.com/shalankwa/go-release-blueprint
    description: |-
      Simple example project for a go-cli application and releases
    formats:
      - deb
      - rpm
    maintainer: Shalanka

brews:
  - name: go-release-blueprint
    repository:
      owner: shalankwa
      name: homebrew-shalankwa
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/shalankwa/homebrew-shalankwa
    commit_author:
      name: shalankwa
      email: shalankwa@gmail.com

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'
